storage: ./.storage
max_body_size: 100mb
plugins: ./plugins

no_proxy: localhost,127.0.0.1

web:
  enable: true # for the ping

auth:
  htpasswd:
    file: ./htpasswd

uplinks:
  npmjs:
    url: https://registry.npmjs.org/

packages:
  'my-private-*':
    access: $all
    publish: $all
    proxy: npmjs
  '**':
    access: $all
    publish: $authenticated
    proxy: npmjs

middlewares:
  audit:
    enabled: true

logs:
  - { type: stdout, format: pretty, level: http }